Add Podcast show
devscast/devscast.org pull request #28
Opened 2023-10-12 12:33 UTC by Tresor-ilunga

* Add Podcast show

2023-10-12 12:46 UTC, bernard-ng requested changes
Dans le controller du podcast la method show te montre quelle variable a été envoyé à la vue, utilisé cette variable pour afficher les informations sur la page détails, les informations doivent venir de l'entité Épisode

2023-10-12 12:46 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                            E32. Raïssa Mandeng. Comment développer sa communauté (WTM Douala)
Il faut mettre le titre qui vient de la base de donnée {{ data.name }}

2023-10-12 12:46 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                                <span>12, Avril, 2023</span>
La date de la base de donnée

2023-10-12 12:46 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                                <span>10min de lecture</span>
La durée de la base de donnée

2023-10-12 12:46 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                                </p>
Ici c'est la description de la base de donnée aussi

2023-10-12 12:48 UTC, Tresor-ilunga commented
D'accord

Le jeu. 12 oct. 2023 à 14:46, Bernard Ngandu ***@***.***> a
écrit :

> ***@***.**** requested changes on this pull request.
>
> Dans le controller du podcast la method show te montre quelle variable a
> été envoyé à la vue, utilisé cette variable pour afficher les informations
> sur la page détails, les informations doivent venir de l'entité Épisode
> ------------------------------
>
> In templates/app/domain/content/podcast/episode/show.html.twig
> <https://github.com/devscast/devscast.org/pull/28#discussion_r1356756657>:
>
> > @@ -1,3 +1,236 @@
> -{{ data.name }} <br> {{ data.contentType.translationKey | trans([], 'content') }}
> +{% extends ***@***.***/shared/layout/base.html.twig' %}
> +<twig:block name="content">
> +    <div class="content-background">
> +        <div class="md:mt-6">
> +            <div class="px-4 lg:px-5 xl:px-8">
> +                <div class="flex flex-col gap-10 sm:flex-row mt-6 md:mt-0 mb-10">
> +                    <div class="sm:w-40 md:w-48 lg:w-56 sm:min-w-[10rem] md:min-w-[12rem] lg:min-w-[14]">
> +                        <img src="https://devscast.tech/uploads/thumbnails/podcasts/comment-developper-sa-communaute-wtm-douala.png" alt="podcast cover" class="w-full aspect-square object-cover rounded-md">
> +                    </div>
> +                    <div class="">
> +                        <h1 class="font-semibold text-xl text-fg-heading1">
> +                            E32. Raïssa Mandeng. Comment développer sa communauté (WTM Douala)
>
> Il faut mettre le titre qui vient de la base de donnée {{ data.name }}
> ------------------------------
>
> In templates/app/domain/content/podcast/episode/show.html.twig
> <https://github.com/devscast/devscast.org/pull/28#discussion_r1356756968>:
>
> > +    <div class="content-background">
> +        <div class="md:mt-6">
> +            <div class="px-4 lg:px-5 xl:px-8">
> +                <div class="flex flex-col gap-10 sm:flex-row mt-6 md:mt-0 mb-10">
> +                    <div class="sm:w-40 md:w-48 lg:w-56 sm:min-w-[10rem] md:min-w-[12rem] lg:min-w-[14]">
> +                        <img src="https://devscast.tech/uploads/thumbnails/podcasts/comment-developper-sa-communaute-wtm-douala.png" alt="podcast cover" class="w-full aspect-square object-cover rounded-md">
> +                    </div>
> +                    <div class="">
> +                        <h1 class="font-semibold text-xl text-fg-heading1">
> +                            E32. Raïssa Mandeng. Comment développer sa communauté (WTM Douala)
> +                        </h1>
> +                        <div class="flex gap-x-2 items-center flex-1 mt-3 justify-between text-fg">
> +                            <div class="flex items-center gap-x-1.5 text-sm">
> +                                <span>10min de lecture</span>
> +                                <span class="w-1 h-1 rounded-full bg-fg"></span>
> +                                <span>12, Avril, 2023</span>
>
> La date de la base de donnée
> ------------------------------
>
> In templates/app/domain/content/podcast/episode/show.html.twig
> <https://github.com/devscast/devscast.org/pull/28#discussion_r1356757359>:
>
> > +{% extends ***@***.***/shared/layout/base.html.twig' %}
> +<twig:block name="content">
> +    <div class="content-background">
> +        <div class="md:mt-6">
> +            <div class="px-4 lg:px-5 xl:px-8">
> +                <div class="flex flex-col gap-10 sm:flex-row mt-6 md:mt-0 mb-10">
> +                    <div class="sm:w-40 md:w-48 lg:w-56 sm:min-w-[10rem] md:min-w-[12rem] lg:min-w-[14]">
> +                        <img src="https://devscast.tech/uploads/thumbnails/podcasts/comment-developper-sa-communaute-wtm-douala.png" alt="podcast cover" class="w-full aspect-square object-cover rounded-md">
> +                    </div>
> +                    <div class="">
> +                        <h1 class="font-semibold text-xl text-fg-heading1">
> +                            E32. Raïssa Mandeng. Comment développer sa communauté (WTM Douala)
> +                        </h1>
> +                        <div class="flex gap-x-2 items-center flex-1 mt-3 justify-between text-fg">
> +                            <div class="flex items-center gap-x-1.5 text-sm">
> +                                <span>10min de lecture</span>
>
> La durée de la base de donnée
> ------------------------------
>
> In templates/app/domain/content/podcast/episode/show.html.twig
> <https://github.com/devscast/devscast.org/pull/28#discussion_r1356758500>:
>
> > +                                <p>
> +                                    Dans ce podcast, nous explorons les différentes façons dont les individus et les communautés
> +                                    peuvent avoir un impact positif sur le monde qui les entoure.
> +                                </p>
> +                                <p>
> +                                    Notre invitée de cette semaine est Raïssa, une femme passionnée de technologie et de développement
> +                                    communautaire. En tant que responsable de la communauté Woman Tech Maker à Douala, Raïssa
> +                                    travaille sans relâche pour encourager et soutenir les femmes dans leur parcours de carrière dans
> +                                    l'industrie de la technologie.
> +                                </p>
> +                                <p>
> +                                    Dans ce podcast, nous explorons les différentes façons dont les individus et les communautés
> +                                    peuvent avoir un impact positif sur le monde qui les entoure.
> +                                </p>
>
> Ici c'est la description de la base de donnée aussi
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/devscast/devscast.org/pull/28#pullrequestreview-1674071312>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AULEAUXK4X5OIBSXDAQDAGTX67RDJANCNFSM6AAAAAA55ROLQQ>
> .
> You are receiving this because you were assigned.Message ID:
> ***@***.***>
>

2023-10-12 13:26 UTC, bernard-ng requested changes

2023-10-12 13:26 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                                <span>{{ data.createdAt }}</span>
C'est une date {{ data.created | date }}

2023-10-12 13:26 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                                    {{ data.content }}
Le contenu est écrit en markdown {{ data.content | markdown_to_html }}

2023-10-12 13:26 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                        <img src="https://devscast.tech/uploads/thumbnails/podcasts/comment-developper-sa-communaute-wtm-douala.png" alt="podcast cover" class="w-full aspect-square object-cover round
Récupère l'image du podcast, comme sur la page index

2023-10-12 21:14 UTC, bernard-ng requested changes

2023-10-12 21:14 UTC, bernard-ng commented on templates/app/domain/content/podcast/episode/show.html.twig
> +                        <img src="{{ data.thumbnail.name ? vich_uploader_asset(this.episode, 'thumbnail_file') : asset('/images/cover.jpg') }}" alt="podcast cover" class="w-full aspect-square object-
`this.episode` n'est pas définit ici, c'est plutôt `data` qu'il faut utiliser

2023-10-13 08:25 UTC, bernard-ng approved these changes

2023-10-13 08:26 UTC, merged